### ISSUE TITLE
Low signal using diseqC

### ISSUE THREAD

**Issue by rubenqs12** [Jalle19/satip-axe#20]
I am using the latest version for Digibit R1, build 18.
The problem is that tunner 3 and 4 do not receive a signal (0 SNR - 0 Signal), and tunner 2 (22% signal), only tunner 1 works well.

With Xoro 8100 if they receive a signal, I rule out problems with the antenna.

I have a monoblock LNB for Astra and Hotbird, and my configuration was:

--diseqc-timing *: 155-54-15-15-15-0 -L 0:1,0:2,0:3

What would be the correct configuration so that they all work well?
Thanks

**Comment by Jalle19** [comment]
I don't use DiseqC so I can't really help you. I suspect this is a configuration issue, not a bug in this firmware - you should try opening a ticket at https://github.com/catalinii/minisatip/issues or creating a post on https://minisatip.org/forum/viewforum.php?f=5.

Please re-open this if this turns out to be a firmware issue.
