### ISSUE TITLE
Copy minisatip configuration from stock firmware on Grund GSSBOX

### ISSUE THREAD

**Issue by rubenkr** [Jalle19/satip-axe#46]
Hi, I try to get minisatip working with following **setup**:

- Quad LNB
- One coax cable attached to adapter #0     
- Device: Grundig GSS400 SAT >IP latest firmware from [here ](https://telestar.de/produkt/digibit-r1/)

**Problem**
- On Stock FW Version V1.25.0.157 DVB-S scan is working (see screens below)
- On latest minisatip 1.2.47~436a845 Command line: minisatip -f -g -z /etc/sysconfig/minisatip -Z *:0 -W 0 it is not working

How can I simply copy the stock firmwares settings into command line code for minisatip? Sorry for the beginner question but I could not find any solution in the git repos. THank you very much !

**Screens**
![Untitled](https://user-images.githubusercontent.com/1043739/206856034-280b264a-2a61-4bc7-bbb2-9f1b9dc3183a.png)

![image](https://user-images.githubusercontent.com/1043739/206855867-b5b5e5cc-ea2f-40d5-bec8-cbbc0cb27876.png)

![image](https://user-images.githubusercontent.com/1043739/206855899-80a94859-e696-4590-afb4-aa57ee6def2e.png)

**Comment by Jalle19** [comment]
As far as I can tell you shouldn't need any specific options. I would recommend installing build 22 instead, there have been many reported issues with builds 23 and 24-rc1.

Since your question is not really related to the firmware but minisatip itself I think you should ask on minisatip.org instead, or the minisatip issue tracker.

**Comment by rubenkr** [comment]
Confirmed. This is a too general question no issue.
